pipeline {
    agent none
    environment { 
        ENV_UB = "/usr/bin/"
    }
    options { 
        skipDefaultCheckout()
        disableConcurrentBuilds()
    }

    stages {
        stage('Checkout scm') {
            agent {label 'Master'}
            steps {
                echo 'Access repo in branch ${env.BRANCH_NAME}'
                checkout scm
                script{
                    echo "Dowmload samconfig from repo todo-list-aws-config of branch: staging"
                    sh """
                        curl -o samconfig.toml https://raw.githubusercontent.com/r4kogama/todo-list-aws-config/refs/heads/staging/samconfig.toml
                        ls -la 
                    """
                }
                
                stash name:'samconfig', includes: 'samconfig.toml'
                stash name:'code', includes:'**/*', excludes: 'samconfig.toml', useDefaultExcludes: false
            }
        }
        stage('Statics') {
            parallel{
                stage('Code Analysis') {
                    agent {label 'Master'}
                    steps{
                        catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                            deleteDir()
                            unstash name:'code'
                            sh """
                                $ENV_UB/flake8 --format=pylint --exit-zero app >flake8.out
                            """
                            recordIssues qualityGates: [
                                [criticality: 'NOTE', integerThreshold: 8, threshold: 8.0, type: 'TOTAL'], 
                                [criticality: 'ERROR', integerThreshold: 10, threshold: 10.0, type: 'TOTAL']],
                                sourceCodeRetention: 'LAST_BUILD', tools: [flake8(pattern: 'flake8.out')],
                                unhealthy: 10
                            deleteDir()
                        }
                    }
                }
                stage('Security') {
                    agent {label 'Master'}
                    steps{
                        catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                            deleteDir()
                            unstash name:'code'
                            sh """
                                $ENV_UB/bandit --exit-zero -r . -f custom -o bandit.out --msg-template "{abspath}:{line}: [{test_id}] {msg}"
                            """
                            recordIssues qualityGates: [
                                [integerThreshold: 2, threshold: 2.0, type: 'TOTAL_ERROR'],
                                [criticality: 'FAILURE', integerThreshold: 4, threshold: 4.0, type: 'TOTAL_HIGH']
                            ], 
                            sourceCodeRetention: 'LAST_BUILD', tools: [pyLint(name: 'Bandit', pattern: 'bandit.out')], unhealthy: 4
                            deleteDir()
                        }
                    }
                }
            }
        }
        stage('Build'){
            agent {label 'Master'}
            steps {
                echo 'Init sam application:'
                catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                    deleteDir()
                    unstash name:'code'
                    sh """
                        sam validate --region us-east-1
                        sam build
                        sleep 3
                    """
                     deleteDir()
                }
            }
        }
        stage('Deploy'){
            agent {label 'Master'}
            steps {
                echo 'Initiating staging environment :'
                catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                    deleteDir()
                    unstash name:'code'
                    unstash name: 'samconfig'
                    sh """
                        sam deploy --no-fail-on-empty-changeset --config-env staging --no-confirm-changeset --no-progressbar
                    """
                    deleteDir()
                }
            }
        }
        stage('Testing'){
            parallel{
                stage('Unit') {
                    agent {label 'Master'}
                    steps {
                        deleteDir()
                        unstash name:'code'
                        sh """
                            export PYTHONPATH="${WORKSPACE}"
                            echo mocking name table
                            export DYNAMODB_TABLE="Name_table_todo"
                            $ENV_UB/pytest test/unit/TestToDo.py --junitxml=result-unit.xml 
                            ls -la
                        """
                        junit testResults: '**/result-*.xml', allowEmptyResults: true
                        deleteDir()
                    }
                }   
                stage('Integration Rest') {
                    agent {label 'Master'}
                    steps {
                        deleteDir()
                        unstash name:'code'
                        script {
                            def BASE_URL = sh( 
                            script: "aws cloudformation describe-stacks --stack-name todo-list-aws-staging --query 'Stacks[0].Outputs[?OutputKey==`BaseUrlApi`].OutputValue' --region us-east-1 --output text",
                            returnStdout: true).trim()
                            withEnv(["BASE_URL=${BASE_URL}"]) {
                                sh """
                                    echo "Init Integration Rest Testing: $BASE_URL"
                                    $ENV_UB/pytest -s test/integration/todoApiTest.py
                                """
                            }
                        }
                        deleteDir()
                    }    
                } 
            }
        }
        stage('Promote'){
            agent {label 'Master'}
            steps {
                unstash name:'code'
                echo 'Merging develop branch to the master branch'
                withCredentials([
                        usernamePassword(credentialsId: 'token-github', 
                        usernameVariable: 'USERNAME', 
                        passwordVariable: 'PASSWORD')]) {
                    sh '''
                        set -x
                        git config user.email "thecureomd@gmail.com"
                        git config user.name "raul garcia"
                        git remote set-url origin https://${USERNAME}:${PASSWORD}@github.com/r4kogama/todo-list-aws.git
                        git remote set-branches --add origin master
                        git fetch origin master
                        git checkout master
                        git pull origin master
                        git merge origin/develop
                        git push origin master
                    '''
                }
                deleteDir()
            }
        }
    }
}
